name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.311'
    
    - name: Old library works with coverage
      run: |
        dotnet run --project OldTUnitTests --coverage --coverage-output-format cobertura --results-directory coverage-old --junit-output-path junit/junit.xml --report-html-filename report/report.html
        echo "Old library has correct coverage:"
        cat coverage-old/*
      
    - name: New library not works with coverage
      run: |
        dotnet run --project NewTUnitTests --coverage --coverage-output-format cobertura --results-directory coverage-new --junit-output-path junit/junit.xml --report-html-filename report/report.html
        echo "New library has not correct coverage:"
        cat coverage-new/*
      
